package com.terrydhariwal.client;

import com.terrydhariwal.model.Activity;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class ActivityClientTest {

    @Test
    public void testGet() throws Exception {
        ActivityClient client = new ActivityClient();
        Activity activity = client.get("1234");
        System.out.println(activity);
        assertNotNull(activity);
    }

    @Test(expected = RuntimeException.class)
    public void testGetWithBadRequest() {
        ActivityClient client = new ActivityClient();
        client.get("123");
    }

    @Test(expected = RuntimeException.class)
    public void testGetWithNotFound() {
        ActivityClient client = new ActivityClient();
        client.get("7777");
    }

    @Test
    public void testGetList() {
        ActivityClient client = new ActivityClient();
        List<Activity> activityList = client.get();
        System.out.println(activityList);
        assertNotNull(activityList);
    }

    @Test
    public void testCreate() {
        ActivityClient client = new ActivityClient();

        Activity activity = new Activity();
        activity.setDescription("Swimming");
        activity.setDuration(90);
        //Don't specify an id here because this is a POST (id should be generated by DB)

        Activity createdActivity =  client.create(activity); //create activity and return it

        assertNotNull(createdActivity);
    }
}